### ISSUE TITLE
Plugin is not loading in Glyphs 3

### ISSUE THREAD

**Issue by harbortype** [mekkablue/SyncSelection#1]
This is what’s in Console.app:

```
default	14:46:34.115009 -0300	Glyphs 3	SyncSelection has encountered a fatal error, and will now terminate.
default	14:46:34.115061 -0300	Glyphs 3	An uncaught exception was raised during execution of the main script:

nosuchclass_error: GlyphsFileFormatUFO

This may mean that an unexpected error has occurred, or that you do not have all of the dependencies for this bundle.
default	14:46:34.115287 -0300	Glyphs 3	Problem with Plugin at Path: /Users/henrique/Library/Application Support/Glyphs 3/Plugins/SyncSelection.glyphsPlugin (!PrincipalClass)
```
Also, it stopped working in Glyphs 2 as well. This is the message I get in the Macro Window:
```
Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/__init__.py", line 1072, in drawForegroundForLayer_options_
TypeError: keepSelectionInSync_() takes exactly 2 arguments (3 given)
```

**Comment by schriftgestalt** [comment]
That is fixed in Glyph 3 (1316).

**Comment by Mark2Mark** [comment]
1a)
I don’t even see the plugin available in the G3 Plugin Manager 😭

1b)
Installed it manually, now get this error in the Macro in Glyphs 3.0b (1335):
`Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/__init__.py", line 1148, in drawForegroundForLayer_options_
  File "plugin.py", line 102, in keepSelectionInSyncWithLayer_blackAndScale_
    otherLayer.selection = None
AttributeError: can't set attribute`

2)
BTW: any thoughts on implementing this into Glyphs? It’s the most essential tool ever, cannot even work without ;)

**Comment by schriftgestalt** [comment]
I fixed this. The plugin will show up in the next update (3002).

Rainer has stared to integrate the functionality into Glyphs but it is not finished. When we get to it, we will remove the plugin.
